apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: cluster-config
spec:
  interval: 2m0s
  sourceRef:
    kind: GitRepository
    name: production
  path: ./infrastructure
  prune: true

